pimpyourtown/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url
from django.views.static import serve

from pimpyourtown import views

urlpatterns = [
    path('', views.IndexView.as_view(), name=''),
    path('city', views.CityView.as_view(), name='city')
]

# Admin
urlpatterns += [
    path('admin/', admin.site.urls),
]

# Static files
urlpatterns += [
    url(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT
        }),
]

pimpyourtown/models.py
from django.db import models

from django.utils.translation import gettext_lazy as _

class County(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'), null=False, blank=False)
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name=_('County')
        verbose_name_plural = _('Counties')

class City(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('Name'), null=False, blank=False)
    county = models.ForeignKey(County, on_delete=models.CASCADE, null=False)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name=_('City')
        verbose_name_plural = _('Cities')
        

pimpyourtown/views.py

from django.views.generic import View, TemplateView

from django.http import HttpResponse
from django.template.response import SimpleTemplateResponse

from pimpyourtown.models import County, City

class IndexView(TemplateView):
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['counties'] = County.objects.all()
        return context

class CityView(View):

    def getCounty(self):
        return County.objects.get(pk=self.request.POST['countyId'])

    def getCountyView(self):
        template = 'content/county_details.html'
        context = {
            'county': self.getCounty()
        }
        return SimpleTemplateResponse(template, context)

    def addCity(self):
        city = City()
        city.name = self.request.POST['newCityName']
        city.county = County.objects.get(pk=self.request.POST['countyId'])
        city.save()
        
        return self.getCountyView()

    def updateCity(self):
        try:
            newCityName = self.request.POST['newCityName']
            city = City.objects.get(pk=self.request.POST['cityId'])
            response = HttpResponse(city.name + ' renamed to ' + newCityName)
            city.name = newCityName
            city.save()
        except City.DoesNotExist:
            response = HttpResponse('No such city')
        return response

    def removeCity(self):
        try:
            city = City.objects.get(pk=self.request.POST['cityId'])
            response = HttpResponse(city.name + ' deleted')
            city.delete()
        except City.DoesNotExist:
            response = HttpResponse('No such city')
        return response

    def post(self, request, *args, **kwargs):
        response = HttpResponse('Invalid operation')
        if request.POST['action'] == "get":
            response = self.getCountyView()
        if request.POST['action'] == "add":
            response = self.addCity()
        if request.POST['action'] == "update":
            response = self.updateCity()
        if request.POST['action'] == "remove":
            response = self.removeCity()
        
        return response

pimpyourtown/templates/base.html
<!DOCTYPE html>
<html lang="hu">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'pimpyourtown/css/index.css' %}">
    <title>{% block title %}{% endblock %} | Pimp Your Town </title>
  </head>
  <body>
    <div class="header">
      {% include "header/header.html" %}
    </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    {% include "footer/footer.html" %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="{% static 'pimpyourtown/js/countyselector.js' %}"></script>
  </body>
</html>

pimpyourtown/templates/content/county_details.html
<h3 class="mb-4"><small class="text-muted">Megye:</small> {{county.name}}</h3>
<div><p class="lead mb-0">Városok:</p></div>
<ul id="cityListContainer">
  {% for city in county.city_set.all %}
    <li id="cityListItem_{{city.pk}}"><p class="label">{{city.name}}</p></li>
  {% endfor %}
</ul>

pimpyourtown/templates/footer/footer.html
<div class="text-center p-4">
  <p><span class="copy-left">©</span> 2021 Copyleft - <strong>Gosztolya Péter</strong></p>
</div>

pimpyourtown/templates/forms/city/add_city_form.html
{% load static %}

<form>
<div class="card-body">
  <div class="row mb-2">
    {% csrf_token %}
    <label for="city_name" class="col-form-label col-lg-4">Új város:</label>
    <div class="col">
      <input type="text" name="city_name" class="form-control"/>
    </div>
  </div>
  <div class="row">
    <div class="col-4"></div>
    <div class="col">
      <button id="addCityBtn" class="btn btn-primary">Felvesz</button>
    </div>
  </div>
</div>
</form>


{% comment %} <div class="row card-body">
  <label for="county" class="col-form-label col-auto">Megye:</label>
  <div class="col">
    <select name="county" id="county-select" class="form-select">
      <option value="" selected="selected" hidden="hidden">Válasszon</option>
      {% for county in counties %}
      <option value="{{county.pk}}">{{ county.name }}</option>
      {% endfor %}
    </select>
  </div>
</div> {% endcomment %}

pimpyourtown/templates/forms/city/edit_city_form.html
{% load static %}
<form id="editCityForm">
  <div class="row">
    {% csrf_token %}
    <input type="hidden" name="cityId" value=""/>
    <div class="col-5">
      <input name="cityName" class="form-control mb-2 mb-sm-0"/>
    </div>
    <div class="col-sm">
      <button type="button" id="removeBtn" class="btn btn-danger">törlés</button>
      <button type="button" id="updateBtn" class="btn btn-primary">módosít</button>
      <button type="button" id="cancelBtn" class="btn btn-secondary">mégse</button>
    </div>
  </div>
</form>

pimpyourtown/templates/forms/county_selector_form.html
<div class="row card-body">
  <label for="county" class="col-form-label col-lg-4">Megye:</label>
  <div class="col">
    <select name="county" id="county-select" class="form-select">
      <option value="" selected="selected" hidden="hidden">Válasszon</option>
      {% for county in counties %}
      <option value="{{county.pk}}">{{ county.name }}</option>
      {% endfor %}
    </select>
  </div>
</div>

pimpyourtown/templates/header/header.html
{% load static %}

<div id="headerCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static "pimpyourtown/img/happy1_resized.png" %}" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="{% static "pimpyourtown/img/happy2_resized.jpg" %}" class="d-block w-100">
    </div>
    <div class="carousel-item">
      <img src="{% static "pimpyourtown/img/happy3_resized.png" %}" class="d-block w-100">
    </div>
    <img class="position-absolute h-50 headerLogo" src="{% static "pimpyourtown/img/logo_big.png" %}">
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#headerCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#headerCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

pimpyourtown/templates/index.html
{% extends 'base.html' %}
{% block title %} Főoldal {% endblock %}

{% block content %}
  <div class="row">
  <h1 class="mt-5">Megérkezett a csodálatos Pimp Your Town webalkalmazás! </h1>
  <p>Kevesled a vagány nevű városok számát? Unod, hogy a haverok nem szállnak le rólad, mert rinyaújnépi vagy? Esetleg az exed szombathelyi, és inkább kitörölnéd az egész várost, úgy ahogy van? Itt a helyed! Csak válaszd ki a megyét, és minden vágyad valóra válik!</p> 
  </div>

  <div class="row">
    <div class="col-xs-6 col-xl-4">
    <div id="countySelectorContainer" class="card m-2">
      {% include 'forms/county_selector_form.html' %}
    </div>
    <div id="addCityForm" class="card m-2">
      {% include 'forms/city/add_city_form.html' %}
    </div>
    </div>
    <div class="col-xs-6 col-xl-5">
    <div id="countyDetailsContainer" class="card m-2">
      {% include "forms/city/edit_city_form.html" %}
      {% for county in counties %}
        <div id="countyDetails_{{county.pk}}" class="card-body">
          {% include "content/county_details.html"%}
        </div>
      {% endfor %}
    </div>
  </div>
  </div>
{% endblock %}